apiVersion: v1
kind: Service
metadata:
  name: mse-api-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: frontend-port
      nodePort: 32500
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mse-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
