version: '3.6'
services:
  minikube:
    image: minikube:latest
    container_name: test-kuber
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
  user-pg:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    volumes:
      - user-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  policy-pg:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: policy
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    volumes:
      - policy-pg-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.0
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - .env
    ports:
      - 9092:9092
  elasticsearch:
    image: elasticsearch:7.17.10
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  user-pg-data:
  policy-pg-data:
  elasticsearch-data:
