apiVersion: v1
kind: Service
metadata:
  name: mse-user-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: frontend-port
      nodePort: 32300
      port: 80
      protocol: TCP
      targetPort: 80
    - name: backend-port
      nodePort: 32301
      port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: mse-user
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
