// Code generated by mockery v2.52.3. DO NOT EDIT.

package services

import (
	context "context"

	entities "gitverse.ru/aleksandr-bebyakov/event-sourcingo/domain/entities"
	events "gitverse.ru/aleksandr-bebyakov/event-sourcingo/domain/events"

	mock "github.com/stretchr/testify/mock"
)

// MockEventHandler is an autogenerated mock type for the EventHandler type
type MockEventHandler struct {
	mock.Mock
}

type MockEventHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventHandler) EXPECT() *MockEventHandler_Expecter {
	return &MockEventHandler_Expecter{mock: &_m.Mock}
}

// HandleEvents provides a mock function with given fields: ctx, history, newEvents, provider
func (_m *MockEventHandler) HandleEvents(ctx context.Context, history []events.Event, newEvents []events.Event, provider entities.AggregateProvider) error {
	ret := _m.Called(ctx, history, newEvents, provider)

	if len(ret) == 0 {
		panic("no return value specified for HandleEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []events.Event, []events.Event, entities.AggregateProvider) error); ok {
		r0 = rf(ctx, history, newEvents, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventHandler_HandleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvents'
type MockEventHandler_HandleEvents_Call struct {
	*mock.Call
}

// HandleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - history []events.Event
//   - newEvents []events.Event
//   - provider entities.AggregateProvider
func (_e *MockEventHandler_Expecter) HandleEvents(ctx interface{}, history interface{}, newEvents interface{}, provider interface{}) *MockEventHandler_HandleEvents_Call {
	return &MockEventHandler_HandleEvents_Call{Call: _e.mock.On("HandleEvents", ctx, history, newEvents, provider)}
}

func (_c *MockEventHandler_HandleEvents_Call) Run(run func(ctx context.Context, history []events.Event, newEvents []events.Event, provider entities.AggregateProvider)) *MockEventHandler_HandleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]events.Event), args[2].([]events.Event), args[3].(entities.AggregateProvider))
	})
	return _c
}

func (_c *MockEventHandler_HandleEvents_Call) Return(_a0 error) *MockEventHandler_HandleEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventHandler_HandleEvents_Call) RunAndReturn(run func(context.Context, []events.Event, []events.Event, entities.AggregateProvider) error) *MockEventHandler_HandleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventHandler creates a new instance of MockEventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventHandler {
	mock := &MockEventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
