// Code generated by mockery v2.52.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProjectionSaver is an autogenerated mock type for the ProjectionSaver type
type MockProjectionSaver struct {
	mock.Mock
}

type MockProjectionSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectionSaver) EXPECT() *MockProjectionSaver_Expecter {
	return &MockProjectionSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, projection
func (_m *MockProjectionSaver) Save(ctx context.Context, projection interface{}) error {
	ret := _m.Called(ctx, projection)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, projection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectionSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectionSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - projection interface{}
func (_e *MockProjectionSaver_Expecter) Save(ctx interface{}, projection interface{}) *MockProjectionSaver_Save_Call {
	return &MockProjectionSaver_Save_Call{Call: _e.mock.On("Save", ctx, projection)}
}

func (_c *MockProjectionSaver_Save_Call) Run(run func(ctx context.Context, projection interface{})) *MockProjectionSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockProjectionSaver_Save_Call) Return(_a0 error) *MockProjectionSaver_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectionSaver_Save_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockProjectionSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectionSaver creates a new instance of MockProjectionSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectionSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectionSaver {
	mock := &MockProjectionSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
