apiVersion: v1
kind: Service
metadata:
  name: mse-policy-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32400
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mse-policy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
